services:
  qrtrail:
    restart: unless-stopped
    image: lcas.lincoln.ac.uk/mhanheide/qrtrail:latest
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/app

  zrok:
      image: openziti/zrok
      restart: unless-stopped
      user: "1001"
      volumes:
        - ${HOME}/.zrok:/.zrok
      environment:
          PFXLOG_NO_JSON: "true"
      command: share reserved "weltrail" --headless
      links:
        - qrtrail
