app_data = {
    "name": "Foundation Year Campus Connect Challenge",
    "description": "Get ready to explore your new university surroundings in a fun and interactive way! The Campus Connect Challenge is designed to help you discover key locations across campus while working together with your group.",
    "author": "Marc Hanheide",
    "html_title": "FY Campus Connect Challenge",
    "project_name": "FY Campus Connect Challenge",
    "keywords": "qr, trail, campus, university, science foundation year, flask, webapp",
    "upload_folder": "static/uploads/",
    "id_dict": {
        "a7f3b8e2-9d4c-4a1e-b5f6-c8d9e0f1a2b3": {
            "image": "artsbridge",
            "title": "Perspective Shot",
            "text": "Capture a photo of your group climbing the stairs, or with the bridge in the background.<br>OR<br>Take a photo of the bridge from an interesting angle—use symmetry, shadows, or reflections.",
            "hint": "Arts Bridge (located between JLC and NDH)",
        },
        "c4d5e6f7-8a9b-4c2d-e3f4-g5h6i7j8k9l0": {
            "image": "inb",
            "title": "Newton's Apple",
            "text": "Recreate the \"apple falling\" moment (ask the web if you don't know the story) —get creative!<br>OR<br>Take a photo of an apple (does not have to be real!) placed somewhere unexpected or symbolic.",
            "hint": "Isaac Newton Building (INB)",
        },
        "e8f9g0h1-2i3j-4k5l-6m7n-o8p9q0r1s2t3": {
            "image": "jlc",
            "title": "Lab Gear Challenge",
            "text": "Take a photo pretending to be ready for lab (e.g., imaginary goggles, gloves).<br>OR<br>Take a close-up photo of lab-themed signage or a building detail.",
            "hint": "Janet Lane-Claypon (JLC)",
        },
        "g2h3i4j5-6k7l-8m9n-0o1p-q2r3s4t5u6v7": {
            "image": "jbl",
            "title": "Science Pose",
            "text": "Strike a \"mad scientist\" pose with your group in front of the building.<br>OR<br>Take a photo of a science-related object or building detail.",
            "hint": "Joseph Banks Laboratories (JBL)",
        },
        "i6j7k8l9-0m1n-2o3p-4q5r-s6t7u8v9w0x1": {
            "image": "lms",
            "title": "Swim with the swan",
            "text": "Act like you are going for a swim in front of the swan mural on the ground floor.<br>OR<br>Capture a detailed or artistic shot of the mural or the DNA sculpture.",
            "hint": "Lincoln Medical School (LMS)",
        },
        "k0l1m2n3-4o5p-6q7r-8s9t-u0v1w2x3y4z5": {
            "image": "mb",
            "title": "Lecture Theatre Leap",
            "text": "Take a fun action shot (e.g., jumping, superhero pose) in the atrium.<br>OR<br>Take a photo of the atrium’s architecture or signage.",
            "hint": "Minerva Building (MB) Atrium",
        },
        "m4n5o6p7-8q9r-0s1t-2u3v-w4x5y6z7a8b9": {
            "image": "mbcafe",
            "title": "Coffee Cheers",
            "text": "Grab a drink (there is free water from the water fountain!) and take a group selfie doing a toast.<br>OR<br>Photograph your drink with a creative background or angle - bonus for latte art or reflections.",
            "hint": "Minerva Building (MB) Cafe",
        },
        "o8p9q0r1-2s3t-4u5v-6w7x-y8z9a0b1c2d3": {
            "image": "ndh",
            "title": "Comfy Corner",
            "text": "Take a break! Pose like you're deep in thought, reading, or just chilling on the seats in front of the lecture theatre.<br>OR<br>Capture a cozy or artistic shot of the seating area - focus on textures, lighting, or composition.",
            "hint": "Nicola de la Haye Building (NDH)",
        },
        "q2r3s4t5-6u7v-8w9x-0y1z-a2b3c4d5e6f7": {
            "image": "sc",
            "title": "Fitness Freeze",
            "text": "Do a fun fitness pose (e.g., plank, yoga, jumping jack) outside.<br>OR<br>Snap a photo of a piece of sports equipment or a motivational poster.",
            "hint": "Sports Centre",
        },
        "s6t7u8v9-0w1x-2y3z-4a5b-c6d7e8f9g0h1": {
            "image": "su",
            "title": "Support Squad",
            "text": "Take a photo with a flyer, poster, or staff member showing student support.<br>OR<br>Take a photo of a flyer, poster, or resource board that highlights student support services.",
            "hint": "Students' Union",
        },
        "u0v1w2x3-4y5z-6a7b-8c9d-e0f1g2h3i4j5": {
            "image": "swc",
            "title": "Wellbeing Boost",
            "text": "\"Thumbs up for wellbeing\" group pose or a relaxed, friendly photo near the entrance.<br>OR<br>Photo of wellbeing posters, entrance signage, or resource table.",
            "hint": "Student Wellbeing Centre",
        },
        "w4x5y6z7-8a9b-0c1d-2e3f-g4h5i6j7k8l9": {
            "image": "ul",
            "title": "Bookworm Moment",
            "text": "Find a quirky book title and take a photo with it.<br>OR<br>Photograph an unusual book title or shelf arrangement.",
            "hint": "University Library",
        },
    },
}
